export const projectsData = [
  {
    title: "Automata",
    imgUrl: "/projects/automata.png",
    desc: "Web Development - Full Stack",
    gitUrl: "https://github.com/TeamCata1yst/automata",
    url: "https://automata-gilt.vercel.app/",
    badge: "Contract Job",
    content: [
      "Automata is a comprehensive, multi-organizational Project and Human Resource Management System designed to support resource coordination, project tracking, and workforce management across interconnected enterprises.",
      "The system features role-based dashboards, automated project workflows, task visualization, and centralized employee management for seamless inter-department collaboration.",
      "The system was made under a freelance contract for an architectural firm in Malviya Nagar, New Delhi.",
    ],
  },
  {
    title: "Purinse",
    imgUrl: "/projects/purinse.png",
    desc: "Web Development - Shopify Liquid",
    url: "https://purinse.com/",
    badge: "Contract Job",
    content: [
      "Developed a fully custom Shopify storefront for Purinse, a home-cleaning essentials brand, using Liquid templates, dynamic product sections, and responsive UI components.",
      "Implemented optimized product pages, custom banners, SEO-friendly metadata, and seamless cart/checkout integrations to boost conversions and user experience.",
      "Delivered a clean, brand-aligned e-commerce experience designed for scalability as the company expands its product line.",
    ],
  },
  {
    title: "Crypt@trix",
    imgUrl: "/projects/crypt.png",
    desc: "Web Development - PHP",
    gitUrl: "https://github.com/PyrotechClub/crypt22",
    content: [
      "Crypt@trix is a competitive tech event platform built for the Pyrotech Club, enabling user registrations, authentication, challenge management, and live scoreboards.",
      "Developed modular PHP components for event flow, problem distribution, and timer-based access to tasks during competitions.",
      "The system was made for a 48 hour event with 300+ concurrent users. The event was organized by the Pyrotech Club at Tagore International School, Vasant Vihar during the annual event Ordin@trix.",
    ],
  },
  {
    title: "ASL Translator",
    imgUrl: "/projects/asl.png",
    desc: "Machine Learning - Python, CNN",
    gitUrl: "https://github.com/NamanChandok/asl-translator",
    content: [
      "A real-time American Sign Language (ASL) translator leveraging Convolutional Neural Networks (CNNs) to interpret hand gestures captured via webcam and convert them into corresponding English text.",
      "This project aims to bridge communication gaps for the deaf and hard-of-hearing community by translating ASL gestures into readable text. Utilizing computer vision and deep learning techniques, the system processes live video input to recognize ASL alphabets.",
      "The system achieved 94.831% accuracy for test images when evaluated on a dataset of 2,520 images representing the 26 letters of the English alphabet and 10 ASL digits.",
    ],
  },
  {
    title: "Outlive Yourself",
    imgUrl: "/projects/outlive.png",
    desc: "Web Development - Next.JS",
    gitUrl: "https://github.com/NamanChandok/outlive",
    url: "https://outlive-yourself.vercel.app/",
    badge: "Contract Job",
    content: [
      "A modern, responsive web application designed to promote the Outlive Yourself campaign, encouraging individuals to consider organ donation and make a lasting impact.",
      "The website promotes organ donation in collaboration with NOTTO and an NGO at Tagore International School, Vasant Vihar.",
      "The website allows users to register themselves and know about organ donation, events and blog posts.",
    ],
  },
  {
    title: "ACM Website",
    imgUrl: "/projects/acm.png",
    desc: "Web Development - Next.JS",
    gitUrl: "https://github.com/NamanChandok/acm-dtc",
    url: "https://acm-dtc.vercel.app/",
    badge: "Award Winner",
    content: [
      "A Next.js-based website for the ACM Student Chapter at DTC, dynamically fetching data from Firebase. The website serves as the digital hub for the student chapter, showcasing events, announcements, blog posts, and member details.",
      "Implemented Firebase-based data fetches, admin updates, and a highly polished UI inspired by modern tech communities.",
      "The project received an Honorable Mention at the ACM Council Awards, recognizing its clean design and robust implementation.",
    ],
  },
  {
    title: "Soluva",
    imgUrl: "/projects/soluva.png",
    desc: "Web Development - Next.JS",
    gitUrl: "https://github.com/NamanChandok/soluva",
    url: "https://soluva.vercel.app/",
    badge: "Contract Job",
    content: [
      "Created a conversion-focused modern landing page for Soluva, a professional services brand, using Next.js and responsive Tailwind-based UI components.",
      "Soluva is an IT-solution agency providing services such as website development, digital marketing, etc.",
      "Developed custom hero sections, feature grids, testimonials, and contact flows optimized for brand credibility with emphasis on clarity, brand consistency, and performance.",
    ],
  },
  {
    title: "Posters",
    imgUrl: "/projects/posters.png",
    desc: "Graphic Design",
    url: "https://drive.google.com/drive/folders/1dDQmHFstzlWjxx6KNQLyFOCAkE3h_JCZ?usp=sharing",
    content: [
      "A curated collection of graphic posters designed for sale and personal use, showcasing expertise in layout, typography, and visual storytelling.",
      "Includes event posters, product marketing creatives, social media graphics, and entertainment programme posters crafted for various industries.",
      "Focuses on clean visual identity, strong color theory, and impactful composition.",
    ],
  },
  {
    title: "Coral",
    imgUrl: "/projects/coral.png",
    desc: "Web Development - Next.JS",
    gitUrl: "https://github.com/NamanChandok/coral",
    url: "https://coral-cyan.vercel.app/",
    content: [
      "Mental health problems are very common. In a single week, at least one in six of us has problems with our mental health, according to the government’s major study of adults in England. Coral is a concept to connect people to psychologists, support groups, therapists, etc. based on their personal needs.",
      "The project was built at a 36 hour hackathon with chosen track Healthcare and Wellness. It won the 2nd Prize at said hackathon.",
      "As a front-end focused prototype, Coral demonstrates strong design sense, purposeful user flow planning and clean implementation.",
    ],
  },
];
