export const projectsData = [
  {
    title: "Automata",
    imgUrl: "/projects/automata.png",
    desc: "Web Development - Full Stack",
    url: "https://github.com/TeamCata1yst/automata",
    badge: "Contract Job",
  },
  {
    title: "ASL Translator",
    imgUrl: "/projects/asl.png",
    desc: "Machine Learning - Python, CNN",
    url: "https://github.com/NamanChandok/asl-translator",
  },
  {
    title: "Crypt@trix",
    imgUrl: "/projects/crypt.png",
    desc: "Web Development - PHP",
    url: "https://github.com/PyrotechClub/crypt22",
  },
  {
    title: "Outlive Yourself",
    imgUrl: "/projects/outlive.png",
    desc: "Web Development - Next.JS",
    url: "https://github.com/NamanChandok/outlive",
    badge: "Contract Job",
  },
  {
    title: "ACM Website",
    imgUrl: "/projects/acm.png",
    desc: "Web Development - Next.JS",
    url: "https://github.com/NamanChandok/acm-dtc",
    badge: "Award Winner",
  },
  {
    title: "Soluva",
    imgUrl: "/projects/soluva.png",
    desc: "Web Development - Next.JS",
    url: "https://github.com/NamanChandok/soluva",
    badge: "Contract Job",
  },
  {
    title: "Posters",
    imgUrl: "/projects/posters.png",
    desc: "Graphic Design",
    url: "https://drive.google.com/drive/folders/1dDQmHFstzlWjxx6KNQLyFOCAkE3h_JCZ?usp=sharing",
  },
  {
    title: "Coral",
    imgUrl: "/projects/coral.png",
    desc: "Web Development - Next.JS",
    url: "https://github.com/NamanChandok/coral",
  },
  {
    title: "HadesTown",
    imgUrl: "/projects/hadestown.png",
    desc: "Web Design - HTML, CSS, JS",
    url: "https://github.com/NamanChandok/alphanode",
  },
];
